---
name: Darwin

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m flake8
      - run: python3 -m unittest
