---
name: Darwin

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: brew install python
      - run: python3 --version
      - run: python3 -m unittest
