---
name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - debian:10
          - debian:9

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: |
          apt-get install -y \
            build-essential \
            ca-certificates \
            python3 \
            python3-pip

      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m flake8
      - run: python3 -m unittest
