---
name: actions

on: [push]

jobs:
  build-darwin:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python3 --version
      - run: python3 -m unittest

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - debian10
          - debian9

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build ${{ matrix.service }}
